"""Initial migration

Revision ID: 972d9384caa5
Revises: 
Create Date: 2024-02-01 17:33:29.924613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972d9384caa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.String(), nullable=False))
        batch_op.create_foreign_key('fk_todo_member_id', 'member', ['member_id'], ['member_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
